import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Placeholder image used for every item until real photos are uploaded via
// the admin panel - do not treat this as final artwork.
const PLACEHOLDER_IMAGE = '/momo.webp';

type SeedItem = {
  slug: string;
  name: string;
  description: string;
  longDescription?: string;
  price: number;
  category:
    | 'momos'
    | 'sides'
    | 'drinks'
    | 'desserts'
    | 'biryanis'
    | 'kattiRolls'
    | 'noodlesRice'
    | 'weekendSpecial'
    | 'streetSnacks'
    | 'lassi';
  spiceLevel: number;
  isVegetarian: boolean;
  isPopular?: boolean;
  isNew?: boolean;
  ingredients: string[];
  allergens: string[];
  preparationTime?: string;
  servingSize?: string;
};

const momoSauce = ['All-purpose flour', 'Nepali spice blend', 'Onion', 'Garlic', 'Ginger'];

const menuItems: SeedItem[] = [
  // ===== HIMALAYAN MOMOS =====
  // Steamed
  {
    slug: 'steamed-veg-momo',
    name: 'Steamed Veg Momo',
    description: 'Handcrafted vegetable momos, steamed to perfection and served with our signature Nepali dipping sauce.',
    price: 11.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Carrot', 'Onion', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'steamed-paneer-momo',
    name: 'Steamed Paneer Momo',
    description: 'Handcrafted paneer momos, steamed to perfection and served with our signature Nepali dipping sauce.',
    price: 12.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Paneer', 'Cabbage', 'Onion', ...momoSauce],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'steamed-chicken-momo',
    name: 'Steamed Chicken Momo',
    description: 'Handcrafted chicken momos, steamed to perfection and served with our signature Nepali dipping sauce.',
    price: 12.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Cilantro', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'steamed-halal-chicken-momo',
    name: 'Steamed Halal Chicken Momo',
    description: 'Handcrafted momos with halal-certified chicken, steamed to perfection and served with our signature Nepali dipping sauce.',
    price: 13.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Halal minced chicken', 'Cilantro', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  // Jhol (Gravy)
  {
    slug: 'jhol-veg-momo',
    name: 'Jhol Veg Momo',
    description: 'Vegetable momos simmered in a warm, tangy Himalayan jhol (gravy) sauce packed with authentic Nepali spices.',
    price: 12.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Carrot', 'Sesame seeds', 'Tomato', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'jhol-paneer-momo',
    name: 'Jhol Paneer Momo',
    description: 'Paneer momos simmered in a warm, tangy Himalayan jhol (gravy) sauce packed with authentic Nepali spices.',
    price: 13.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Paneer', 'Sesame seeds', 'Tomato', ...momoSauce],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'jhol-chicken-momo',
    name: 'Jhol Chicken Momo',
    description: "Our featured dish - chicken momos simmered in a warm, tangy Himalayan jhol (gravy) sauce packed with authentic Nepali spices.",
    price: 13.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: false,
    isPopular: true,
    ingredients: ['Minced chicken', 'Sesame seeds', 'Tomato', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'jhol-halal-chicken-momo',
    name: 'Jhol Halal Chicken Momo',
    description: 'Halal-certified chicken momos simmered in a warm, tangy Himalayan jhol (gravy) sauce packed with authentic Nepali spices.',
    price: 14.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: false,
    isPopular: true,
    ingredients: ['Halal minced chicken', 'Sesame seeds', 'Tomato', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  // Fried
  {
    slug: 'fried-veg-momo',
    name: 'Fried Veg Momo',
    description: 'Crispy deep-fried vegetable momos with a golden crust and juicy filling.',
    price: 12.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Carrot', 'Onion', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'fried-paneer-momo',
    name: 'Fried Paneer Momo',
    description: 'Crispy deep-fried paneer momos with a golden crust and juicy filling.',
    price: 13.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Paneer', 'Cabbage', 'Onion', ...momoSauce],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'fried-chicken-momo',
    name: 'Fried Chicken Momo',
    description: 'Crispy deep-fried chicken momos with a golden crust and juicy filling.',
    price: 13.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Cilantro', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'fried-halal-chicken-momo',
    name: 'Fried Halal Chicken Momo',
    description: 'Crispy deep-fried momos with halal-certified chicken, golden crust and juicy filling.',
    price: 14.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Halal minced chicken', 'Cilantro', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  // Pan Fried / Kothey
  {
    slug: 'kothey-veg-momo',
    name: 'Pan Fried / Kothey Veg Momo',
    description: 'Pan-seared on one side for a crispy base, soft and steamed on top - the best of both worlds, veg style.',
    price: 12.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Carrot', 'Onion', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'kothey-paneer-momo',
    name: 'Pan Fried / Kothey Paneer Momo',
    description: 'Pan-seared on one side for a crispy base, soft and steamed on top - the best of both worlds, paneer style.',
    price: 13.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Paneer', 'Cabbage', 'Onion', ...momoSauce],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'kothey-chicken-momo',
    name: 'Pan Fried / Kothey Chicken Momo',
    description: 'Pan-seared on one side for a crispy base, soft and steamed on top - the best of both worlds, chicken style.',
    price: 13.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Cilantro', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'kothey-halal-chicken-momo',
    name: 'Pan Fried / Kothey Halal Chicken Momo',
    description: 'Pan-seared on one side for a crispy base, soft and steamed on top, made with halal-certified chicken.',
    price: 14.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Halal minced chicken', 'Cilantro', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  // Chilli
  {
    slug: 'chilli-veg-momo',
    name: 'Chilli Veg Momo',
    description: 'Vegetable momos wok-tossed in a fiery chilli garlic sauce with peppers and onions for a bold, spicy kick.',
    price: 13.99,
    category: 'momos',
    spiceLevel: 3,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Bell pepper', 'Onion', 'Chilli sauce', 'Garlic', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'chilli-paneer-momo',
    name: 'Chilli Paneer Momo',
    description: 'Paneer momos wok-tossed in a fiery chilli garlic sauce with peppers and onions for a bold, spicy kick.',
    price: 14.99,
    category: 'momos',
    spiceLevel: 3,
    isVegetarian: true,
    ingredients: ['Paneer', 'Bell pepper', 'Onion', 'Chilli sauce', 'Garlic', ...momoSauce],
    allergens: ['Gluten', 'Dairy', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'chilli-chicken-momo',
    name: 'Chilli Chicken Momo',
    description: 'Chicken momos wok-tossed in a fiery chilli garlic sauce with peppers and onions for a bold, spicy kick.',
    price: 14.99,
    category: 'momos',
    spiceLevel: 3,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Bell pepper', 'Onion', 'Chilli sauce', 'Garlic', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'chilli-halal-chicken-momo',
    name: 'Chilli Halal Chicken Momo',
    description: 'Halal chicken momos wok-tossed in a fiery chilli garlic sauce with peppers and onions for a bold, spicy kick.',
    price: 15.99,
    category: 'momos',
    spiceLevel: 3,
    isVegetarian: false,
    ingredients: ['Halal minced chicken', 'Bell pepper', 'Onion', 'Chilli sauce', 'Garlic', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  // Chef's Special Momos
  {
    slug: 'manchurian-veg-momo',
    name: 'Manchurian Veg Momo',
    description: "Momo Station's chef-special veg momos tossed in a classic Indo-Chinese Manchurian sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station. Halal chicken available upon request for the chicken versions.",
    price: 13.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Carrot', 'Manchurian sauce', 'Garlic', 'Soy sauce', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'manchurian-chicken-momo',
    name: 'Manchurian Chicken Momo',
    description: "Momo Station's chef-special chicken momos tossed in a classic Indo-Chinese Manchurian sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station. Halal chicken available upon request.",
    price: 14.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Manchurian sauce', 'Garlic', 'Soy sauce', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'tandoori-veg-momo',
    name: 'Tandoori Veg Momo',
    description: "Momo Station's chef-special veg momos marinated and tossed in a smoky tandoori spice glaze.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station.",
    price: 13.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Carrot', 'Tandoori spice blend', 'Yogurt', ...momoSauce],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'tandoori-chicken-momo',
    name: 'Tandoori Chicken Momo',
    description: "Momo Station's chef-special chicken momos marinated and tossed in a smoky tandoori spice glaze.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station. Halal chicken available upon request.",
    price: 14.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Tandoori spice blend', 'Yogurt', ...momoSauce],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'butter-chicken-momo',
    name: 'Butter Chicken Momo',
    description: "Momo Station's chef-special chicken momos tossed in a rich, creamy butter chicken sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station. Halal chicken available upon request.",
    price: 14.99,
    category: 'momos',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Tomato', 'Butter', 'Cream', 'Garam masala', ...momoSauce],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'kurkure-veg-momo',
    name: 'Kurkure Veg Momo',
    description: "Momo Station's chef-special veg momos coated in a crispy, crunchy kurkure batter and deep fried.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station.",
    price: 13.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Carrot', 'Crispy batter coating', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'kurkure-chicken-momo',
    name: 'Kurkure Chicken Momo',
    description: "Momo Station's chef-special chicken momos coated in a crispy, crunchy kurkure batter and deep fried.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station. Halal chicken available upon request.",
    price: 14.99,
    category: 'momos',
    spiceLevel: 2,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Crispy batter coating', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'devil-veg-momo',
    name: 'Devil Veg Momo',
    description: "Momo Station's chef-special veg momos tossed in a fiery 'devil' style chilli-garlic-soy sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station.",
    price: 13.99,
    category: 'momos',
    spiceLevel: 3,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Bell pepper', 'Onion', 'Chilli sauce', 'Soy sauce', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'devil-chicken-momo',
    name: 'Devil Chicken Momo',
    description: "Momo Station's chef-special chicken momos tossed in a fiery 'devil' style chilli-garlic-soy sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station. Halal chicken available upon request.",
    price: 14.99,
    category: 'momos',
    spiceLevel: 3,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Bell pepper', 'Onion', 'Chilli sauce', 'Soy sauce', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'red-dragon-veg-momo',
    name: 'Red Dragon Veg Momo',
    description: "Momo Station's chef-special veg momos wok-tossed in a bold, spicy red dragon chilli sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station.",
    price: 13.99,
    category: 'momos',
    spiceLevel: 3,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Bell pepper', 'Red chilli sauce', 'Garlic', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'red-dragon-chicken-momo',
    name: 'Red Dragon Chicken Momo',
    description: "Momo Station's chef-special chicken momos wok-tossed in a bold, spicy red dragon chilli sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station. Halal chicken available upon request.",
    price: 14.99,
    category: 'momos',
    spiceLevel: 3,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Bell pepper', 'Red chilli sauce', 'Garlic', ...momoSauce],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'honey-garlic-veg-momo',
    name: 'Honey Garlic Veg Momo',
    description: "Momo Station's chef-special veg momos glazed in a sweet and savory honey garlic sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station.",
    price: 13.99,
    category: 'momos',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Cabbage', 'Carrot', 'Honey', 'Garlic', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },
  {
    slug: 'honey-garlic-chicken-momo',
    name: 'Honey Garlic Chicken Momo',
    description: "Momo Station's chef-special chicken momos glazed in a sweet and savory honey garlic sauce.",
    longDescription: "Part of our Chef's Special Momo collection - unique fusion flavors crafted by Momo Station. Halal chicken available upon request.",
    price: 14.99,
    category: 'momos',
    spiceLevel: 0,
    isVegetarian: false,
    ingredients: ['Minced chicken', 'Honey', 'Garlic', ...momoSauce],
    allergens: ['Gluten'],
    preparationTime: '15-20 mins',
    servingSize: '10 pieces',
  },

  // ===== HIMALAYAN NOODLES & FRIED RICE =====
  {
    slug: 'chowmein-veg',
    name: 'Chowmein Veg',
    description: 'Wok-tossed noodles with fresh seasonal vegetables in a savory Himalayan-style sauce.',
    price: 12.99,
    category: 'noodlesRice',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Noodles', 'Cabbage', 'Carrot', 'Bell pepper', 'Soy sauce'],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '10-15 mins',
    servingSize: '1 plate',
  },
  {
    slug: 'chowmein-chicken',
    name: 'Chowmein Chicken',
    description: 'Wok-tossed noodles with chicken and fresh vegetables in a savory Himalayan-style sauce.',
    price: 14.99,
    category: 'noodlesRice',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Noodles', 'Chicken', 'Cabbage', 'Carrot', 'Soy sauce'],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '10-15 mins',
    servingSize: '1 plate',
  },
  {
    slug: 'keema-noodles',
    name: 'Keema Noodles',
    description: 'Udon noodles tossed with ground chicken keema and bok choy in a savory sauce.',
    price: 14.99,
    category: 'noodlesRice',
    spiceLevel: 2,
    isVegetarian: false,
    ingredients: ['Udon noodles', 'Ground chicken', 'Bok choy', 'Garlic', 'Soy sauce'],
    allergens: ['Gluten', 'Soy'],
    preparationTime: '10-15 mins',
    servingSize: '1 plate',
  },
  {
    slug: 'fried-rice-veg',
    name: 'Fried Rice Veg',
    description: 'Wok-fried rice with fresh vegetables and savory seasoning.',
    price: 12.99,
    category: 'noodlesRice',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Rice', 'Carrot', 'Peas', 'Onion', 'Soy sauce'],
    allergens: ['Soy'],
    preparationTime: '10-15 mins',
    servingSize: '1 plate',
  },
  {
    slug: 'golden-egg-fried-rice',
    name: 'Golden Egg Fried Rice',
    description: 'Wok-fried rice tossed with fluffy scrambled egg for a golden, savory finish.',
    price: 13.99,
    category: 'noodlesRice',
    spiceLevel: 0,
    isVegetarian: false,
    ingredients: ['Rice', 'Egg', 'Carrot', 'Onion', 'Soy sauce'],
    allergens: ['Egg', 'Soy'],
    preparationTime: '10-15 mins',
    servingSize: '1 plate',
  },
  {
    slug: 'fried-rice-chicken',
    name: 'Fried Rice Chicken',
    description: 'Wok-fried rice with chicken, vegetables, and savory seasoning.',
    price: 14.99,
    category: 'noodlesRice',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Rice', 'Chicken', 'Carrot', 'Onion', 'Soy sauce'],
    allergens: ['Soy'],
    preparationTime: '10-15 mins',
    servingSize: '1 plate',
  },

  // ===== HIMALAYAN KATTI ROLL (WRAPS) =====
  {
    slug: 'egg-katti-roll',
    name: 'Egg Katti Roll',
    description: 'Griddled paratha wrap filled with fluffy scrambled egg and tangy chutney.',
    price: 9.99,
    category: 'kattiRolls',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Paratha', 'Egg', 'Onion', 'Chutney'],
    allergens: ['Gluten', 'Egg'],
    preparationTime: '10-15 mins',
    servingSize: '1 wrap',
  },
  {
    slug: 'crispy-chicken-katti-roll',
    name: 'Crispy Chicken Katti Roll',
    description: 'Griddled paratha wrap filled with crispy fried chicken, onions, and tangy chutney.',
    price: 11.99,
    category: 'kattiRolls',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Paratha', 'Crispy chicken', 'Onion', 'Chutney'],
    allergens: ['Gluten'],
    preparationTime: '10-15 mins',
    servingSize: '1 wrap',
  },
  {
    slug: 'crispy-butter-chicken-katti-roll',
    name: 'Crispy Butter Chicken Katti Roll',
    description: 'Griddled paratha wrap filled with crispy chicken tossed in creamy butter chicken sauce.',
    price: 12.99,
    category: 'kattiRolls',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Paratha', 'Crispy chicken', 'Butter chicken sauce', 'Onion'],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '10-15 mins',
    servingSize: '1 wrap',
  },

  // ===== HIMALAYAN STREET SNACKS =====
  {
    slug: 'fries',
    name: 'Fries',
    description: 'Golden, crispy French fries seasoned to perfection.',
    price: 3.99,
    category: 'streetSnacks',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Potato', 'Salt', 'Seasoning'],
    allergens: [],
    preparationTime: '5-10 mins',
    servingSize: '1 order',
  },
  {
    slug: 'samosa-with-masala-chai',
    name: 'Samosa (2pcs) with Masala Chai',
    description: 'Two crispy, golden samosas filled with spiced potatoes and peas, served with a cup of masala chai.',
    price: 5.99,
    category: 'streetSnacks',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Potato', 'Peas', 'Flour', 'Masala chai'],
    allergens: ['Gluten', 'Dairy'],
    preparationTime: '10-15 mins',
    servingSize: '2 pieces + 1 chai',
  },
  {
    slug: 'chatpate',
    name: 'Chatpate (Dry / Gilo)',
    description: 'Nepali street-style puffed rice salad tossed with spicy tangy masala, potatoes, and chickpeas - served dry or with gravy.',
    price: 5.99,
    category: 'streetSnacks',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Puffed rice', 'Potato', 'Chickpeas', 'Onion', 'Tangy masala'],
    allergens: [],
    preparationTime: '5-10 mins',
    servingSize: '1 bowl',
  },
  {
    slug: 'wai-wai-sadheko',
    name: 'Wai Wai Sadheko',
    description: 'Crushed Wai Wai instant noodles tossed Nepali-style with onions, tomato, cilantro, and a tangy spicy dressing.',
    price: 5.99,
    category: 'streetSnacks',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Wai Wai noodles', 'Onion', 'Tomato', 'Cilantro', 'Lemon'],
    allergens: ['Gluten'],
    preparationTime: '5-10 mins',
    servingSize: '1 bowl',
  },
  {
    slug: 'spicy-mustang-potato',
    name: 'Spicy Mustang Potato',
    description: 'Crispy fried potatoes tossed in a bold Mustang-style spicy masala.',
    price: 6.99,
    category: 'streetSnacks',
    spiceLevel: 3,
    isVegetarian: true,
    ingredients: ['Potato', 'Timur (Sichuan pepper)', 'Chilli', 'Garlic'],
    allergens: [],
    preparationTime: '10-15 mins',
    servingSize: '1 order',
  },
  {
    slug: 'himalayan-chicken-burger',
    name: 'Himalayan Chicken Burger (Spicy / Non-Spicy)',
    description: 'Juicy fried chicken burger, available spicy or non-spicy, with fresh lettuce and our house sauce.',
    price: 6.99,
    category: 'streetSnacks',
    spiceLevel: 2,
    isVegetarian: false,
    ingredients: ['Chicken patty', 'Bun', 'Lettuce', 'House sauce'],
    allergens: ['Gluten'],
    preparationTime: '10-15 mins',
    servingSize: '1 burger',
  },
  {
    slug: 'pani-puri',
    name: 'Pani Puri',
    description: 'Crispy hollow puris filled with spiced potato, chickpeas, and tangy tamarind water.',
    price: 7.99,
    category: 'streetSnacks',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Puri', 'Potato', 'Chickpeas', 'Tamarind water', 'Mint'],
    allergens: ['Gluten'],
    preparationTime: '10-15 mins',
    servingSize: '6 pieces',
  },
  {
    slug: 'chicken-sausage-fried',
    name: 'Chicken Sausage Fried',
    description: "Pan-fried chicken sausages tossed in Momo Station's signature sauce.",
    price: 7.99,
    category: 'streetSnacks',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Chicken sausage', 'Momo Station signature sauce', 'Onion'],
    allergens: [],
    preparationTime: '10-15 mins',
    servingSize: '1 order',
  },
  {
    slug: 'potato-chips-chilli',
    name: 'Potato Chips Chilli',
    description: 'Crispy potato chips wok-tossed with chilli, garlic, and onions.',
    price: 7.99,
    category: 'streetSnacks',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Potato chips', 'Chilli', 'Garlic', 'Onion'],
    allergens: [],
    preparationTime: '10-15 mins',
    servingSize: '1 order',
  },
  {
    slug: 'butter-chicken-poutine',
    name: 'Butter Chicken Poutine',
    description: 'Crispy fries topped with tender butter chicken, sauce, and melted cheese curds.',
    price: 9.99,
    category: 'streetSnacks',
    spiceLevel: 1,
    isVegetarian: false,
    isNew: true,
    ingredients: ['Fries', 'Butter chicken', 'Cheese curds', 'Gravy'],
    allergens: ['Dairy'],
    preparationTime: '10-15 mins',
    servingSize: '1 order',
  },
  {
    slug: 'chicken-wings-salt-pepper',
    name: 'Chicken Wings Salt & Pepper (8pcs)',
    description: 'Crispy fried chicken wings tossed in salt and pepper seasoning.',
    price: 9.99,
    category: 'streetSnacks',
    spiceLevel: 1,
    isVegetarian: false,
    ingredients: ['Chicken wings', 'Salt', 'Black pepper', 'Garlic'],
    allergens: [],
    preparationTime: '15-20 mins',
    servingSize: '8 pieces',
  },
  {
    slug: 'chicken-wings-honey-garlic',
    name: 'Chicken Wings Honey & Garlic (8pcs)',
    description: 'Crispy fried chicken wings glazed in a sweet honey garlic sauce.',
    price: 10.99,
    category: 'streetSnacks',
    spiceLevel: 0,
    isVegetarian: false,
    ingredients: ['Chicken wings', 'Honey', 'Garlic'],
    allergens: [],
    preparationTime: '15-20 mins',
    servingSize: '8 pieces',
  },
  {
    slug: 'chicken-wings-chilli',
    name: 'Chicken Wings Chilli (8pcs)',
    description: 'Crispy fried chicken wings tossed in a fiery chilli sauce.',
    price: 11.99,
    category: 'streetSnacks',
    spiceLevel: 3,
    isVegetarian: false,
    ingredients: ['Chicken wings', 'Chilli sauce', 'Garlic'],
    allergens: [],
    preparationTime: '15-20 mins',
    servingSize: '8 pieces',
  },
  {
    slug: 'chicken-chilli',
    name: 'Chicken Chilli',
    description: 'Wok-tossed chicken with bell peppers, onions, and a bold chilli garlic sauce.',
    price: 13.99,
    category: 'streetSnacks',
    spiceLevel: 3,
    isVegetarian: false,
    ingredients: ['Chicken', 'Bell pepper', 'Onion', 'Chilli sauce', 'Garlic'],
    allergens: ['Soy'],
    preparationTime: '15-20 mins',
    servingSize: '1 order',
  },
  {
    slug: 'paneer-chilli',
    name: 'Paneer Chilli',
    description: 'Wok-tossed paneer with bell peppers, onions, and a bold chilli garlic sauce.',
    price: 13.99,
    category: 'streetSnacks',
    spiceLevel: 3,
    isVegetarian: true,
    ingredients: ['Paneer', 'Bell pepper', 'Onion', 'Chilli sauce', 'Garlic'],
    allergens: ['Dairy', 'Soy'],
    preparationTime: '15-20 mins',
    servingSize: '1 order',
  },

  // ===== HIMALAYAN BIRYANIS =====
  {
    slug: 'veg-biryani',
    name: 'Veg Biryani',
    description: 'Fragrant basmati rice slow-cooked with mixed vegetables and traditional biryani spices.',
    price: 13.99,
    category: 'biryanis',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Basmati rice', 'Mixed vegetables', 'Biryani spices', 'Saffron'],
    allergens: [],
    preparationTime: '20-25 mins',
    servingSize: '1 bowl',
  },
  {
    slug: 'paneer-biryani',
    name: 'Paneer Biryani',
    description: 'Fragrant basmati rice slow-cooked with paneer and traditional biryani spices.',
    price: 15.99,
    category: 'biryanis',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Basmati rice', 'Paneer', 'Biryani spices', 'Saffron'],
    allergens: ['Dairy'],
    preparationTime: '20-25 mins',
    servingSize: '1 bowl',
  },
  {
    slug: 'chicken-biryani',
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice slow-cooked with tender chicken and traditional biryani spices.',
    price: 15.99,
    category: 'biryanis',
    spiceLevel: 2,
    isVegetarian: false,
    isPopular: true,
    ingredients: ['Basmati rice', 'Chicken', 'Biryani spices', 'Saffron'],
    allergens: [],
    preparationTime: '20-25 mins',
    servingSize: '1 bowl',
  },
  {
    slug: 'mutton-biryani',
    name: 'Mutton Biryani',
    description: 'Fragrant basmati rice slow-cooked with tender mutton and traditional biryani spices.',
    price: 17.99,
    category: 'biryanis',
    spiceLevel: 2,
    isVegetarian: false,
    ingredients: ['Basmati rice', 'Mutton', 'Biryani spices', 'Saffron'],
    allergens: [],
    preparationTime: '25-30 mins',
    servingSize: '1 bowl',
  },

  // ===== HIMALAYAN SPECIAL LASSI =====
  {
    slug: 'himalayan-janakpuri-sweet-lassi',
    name: 'Himalayan Janakpuri Sweet Lassi',
    description: 'Traditional sweet yogurt lassi, a classic Nepali favorite.',
    price: 4.99,
    category: 'lassi',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Yogurt', 'Sugar', 'Cardamom'],
    allergens: ['Dairy'],
    preparationTime: '5 mins',
    servingSize: '1 glass',
  },
  {
    slug: 'himalayan-banana-lassi',
    name: 'Himalayan Banana Lassi',
    description: 'Creamy blended yogurt lassi with fresh banana.',
    price: 5.99,
    category: 'lassi',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Yogurt', 'Banana', 'Sugar'],
    allergens: ['Dairy'],
    preparationTime: '5 mins',
    servingSize: '1 glass',
  },
  {
    slug: 'himalayan-mango-lassi',
    name: 'Himalayan Mango Lassi',
    description: 'Creamy blended yogurt lassi with fresh mango.',
    price: 5.99,
    category: 'lassi',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Yogurt', 'Mango', 'Sugar'],
    allergens: ['Dairy'],
    preparationTime: '5 mins',
    servingSize: '1 glass',
  },
  {
    slug: 'himalayan-strawberry-lassi',
    name: 'Himalayan Strawberry Lassi',
    description: 'Creamy blended yogurt lassi with fresh strawberry.',
    price: 5.99,
    category: 'lassi',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Yogurt', 'Strawberry', 'Sugar'],
    allergens: ['Dairy'],
    preparationTime: '5 mins',
    servingSize: '1 glass',
  },
  {
    slug: 'himalayan-blueberry-lassi',
    name: 'Himalayan Blueberry Lassi',
    description: 'Creamy blended yogurt lassi with fresh blueberry.',
    price: 5.99,
    category: 'lassi',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Yogurt', 'Blueberry', 'Sugar'],
    allergens: ['Dairy'],
    preparationTime: '5 mins',
    servingSize: '1 glass',
  },
  {
    slug: 'himalayan-avocado-lassi',
    name: 'Himalayan Avocado Lassi',
    description: 'Creamy blended yogurt lassi with fresh avocado.',
    price: 5.99,
    category: 'lassi',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Yogurt', 'Avocado', 'Sugar'],
    allergens: ['Dairy'],
    preparationTime: '5 mins',
    servingSize: '1 glass',
  },

  // ===== DRINKS =====
  {
    slug: 'spring-water-canned-pop',
    name: 'Spring Water / Canned Pop',
    description: 'Bottled spring water or your choice of canned soda.',
    price: 1.5,
    category: 'drinks',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: [],
    allergens: [],
    servingSize: '1 bottle/can',
  },
  {
    slug: 'masala-coke',
    name: 'Masala Coke',
    description: 'Coca-Cola infused with a zesty Nepali masala spice blend.',
    price: 2.99,
    category: 'drinks',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Coca-Cola', 'Masala spice blend', 'Lemon'],
    allergens: [],
    servingSize: '1 glass',
  },
  {
    slug: 'virgin-masala-mojito',
    name: 'Virgin Masala Mojito',
    description: 'A refreshing non-alcoholic mojito with mint, lime, and a spiced masala twist.',
    price: 2.99,
    category: 'drinks',
    spiceLevel: 1,
    isVegetarian: true,
    ingredients: ['Mint', 'Lime', 'Soda water', 'Masala spice blend'],
    allergens: [],
    servingSize: '1 glass',
  },

  // ===== WEEKEND SPECIAL: HIMALAYAN THAKALI KHANA SET =====
  {
    slug: 'veg-thakali-khana-set',
    name: 'Himalayan Thakali Khana Set (Veg)',
    description: 'Traditional Nepali Thakali thali featuring rice, lentils, seasonal vegetable curries, and pickle - vegetarian, weekends only.',
    longDescription: 'Available weekends only. A full traditional Thakali set meal featuring daal (lentils), bhat (rice), seasonal tarkari (vegetable curries), achar (pickle), and more.',
    price: 16.99,
    category: 'weekendSpecial',
    spiceLevel: 2,
    isVegetarian: true,
    ingredients: ['Rice', 'Lentils', 'Seasonal vegetables', 'Pickle', 'Ghee'],
    allergens: ['Dairy'],
    preparationTime: '20-25 mins',
    servingSize: '1 thali',
  },
  {
    slug: 'chicken-thakali-khana-set',
    name: 'Himalayan Thakali Khana Set (Chicken)',
    description: 'Traditional Nepali Thakali thali featuring rice, lentils, chicken curry, seasonal vegetables, and pickle - weekends only.',
    longDescription: 'Available weekends only. A full traditional Thakali set meal featuring daal (lentils), bhat (rice), chicken curry, seasonal tarkari (vegetable curries), achar (pickle), and more.',
    price: 17.99,
    category: 'weekendSpecial',
    spiceLevel: 2,
    isVegetarian: false,
    ingredients: ['Rice', 'Lentils', 'Chicken curry', 'Seasonal vegetables', 'Pickle'],
    allergens: ['Dairy'],
    preparationTime: '20-25 mins',
    servingSize: '1 thali',
  },
  {
    slug: 'goat-thakali-khana-set',
    name: 'Himalayan Thakali Khana Set (Goat)',
    description: 'Traditional Nepali Thakali thali featuring rice, lentils, goat curry, seasonal vegetables, and pickle - weekends only.',
    longDescription: 'Available weekends only. A full traditional Thakali set meal featuring daal (lentils), bhat (rice), goat curry, seasonal tarkari (vegetable curries), achar (pickle), and more.',
    price: 19.99,
    category: 'weekendSpecial',
    spiceLevel: 2,
    isVegetarian: false,
    ingredients: ['Rice', 'Lentils', 'Goat curry', 'Seasonal vegetables', 'Pickle'],
    allergens: ['Dairy'],
    preparationTime: '25-30 mins',
    servingSize: '1 thali',
  },
];

async function main() {
  console.log('Seeding menu with the real Himalayan Express Momo Station menu...');

  await prisma.menuItem.deleteMany({});
  console.log('Cleared existing menu items');

  for (const item of menuItems) {
    await prisma.menuItem.create({
      data: {
        ...item,
        image: PLACEHOLDER_IMAGE,
      },
    });
    console.log(`Created: ${item.name}`);
  }

  console.log(`\nSeeded ${menuItems.length} menu items successfully!`);
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
